import { FIA_CATEGORIES, EVENT_TYPES, EVENT_STATUS } from '../models/SportEvent.js';
import { PIRELLI_COMPOUNDS } from '../models/TireTestEvent.js';
import { DRIVER_ROLES } from '../models/Driver.js';
import { CAR_STATUS } from '../models/Car.js';
import { RACE_STATUS } from '../models/RaceResult.js';
import { USER_ROLES } from '../models/User.js';

export const INITIAL_TEAMS = [
  {
    id: 'team-ferrari',
    nombre: 'Scuderia Ferrari HP',
    nombreCompleto: 'Scuderia Ferrari HP F1 Team',
    pais: 'Italia',
    sede: 'Maranello, Módena, Italia',
    directorEquipo: 'Frédéric Vasseur',
    directorTecnico: 'Loïc Serra',
    chasis: 'SF-26',
    unidadPotencia: 'Ferrari 066/12 V6 Turbo Híbrido',
    colorPrimario: '#E80020',
    colorSecundario: '#1E1E1E',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 380,
    posicionCampeonato: 1,
    campeonatosConstructores: 16
  },
  {
    id: 'team-redbull',
    nombre: 'Oracle Red Bull Racing',
    nombreCompleto: 'Oracle Red Bull Racing F1 Team',
    pais: 'Austria / Reino Unido',
    sede: 'Milton Keynes, Reino Unido',
    directorEquipo: 'Christian Horner',
    directorTecnico: 'Pierre Waché',
    chasis: 'RB22',
    unidadPotencia: 'Honda RBPT RBPTH003',
    colorPrimario: '#1E41FF',
    colorSecundario: '#CC1E4A',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 365,
    posicionCampeonato: 2,
    campeonatosConstructores: 6
  },
  {
    id: 'team-mclaren',
    nombre: 'McLaren Formula 1 Team',
    nombreCompleto: 'McLaren Formula 1 Team',
    pais: 'Reino Unido',
    sede: 'Woking, Surrey, Reino Unido',
    directorEquipo: 'Andrea Stella',
    directorTecnico: 'Peter Prodromou',
    chasis: 'MCL39',
    unidadPotencia: 'Mercedes-AMG M17 E Performance',
    colorPrimario: '#FF8000',
    colorSecundario: '#47C7FC',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 340,
    posicionCampeonato: 3,
    campeonatosConstructores: 8
  },
  {
    id: 'team-mercedes',
    nombre: 'Mercedes-AMG PETRONAS',
    nombreCompleto: 'Mercedes-AMG PETRONAS Formula One Team',
    pais: 'Alemania / Reino Unido',
    sede: 'Brackley, Northamptonshire, Reino Unido',
    directorEquipo: 'Toto Wolff',
    directorTecnico: 'James Allison',
    chasis: 'W17',
    unidadPotencia: 'Mercedes-AMG M17 E Performance',
    colorPrimario: '#00A19B',
    colorSecundario: '#C0C0C0',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 290,
    posicionCampeonato: 4,
    campeonatosConstructores: 8
  },
  {
    id: 'team-astonmartin',
    nombre: 'Aston Martin Aramco F1',
    nombreCompleto: 'Aston Martin Aramco Formula One Team',
    pais: 'Reino Unido',
    sede: 'Silverstone, Northamptonshire, Reino Unido',
    directorEquipo: 'Mike Krack',
    directorTecnico: 'Dan Fallows',
    chasis: 'AMR26',
    unidadPotencia: 'Mercedes-AMG M17 E Performance',
    colorPrimario: '#00594F',
    colorSecundario: '#CEDC00',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 120,
    posicionCampeonato: 5,
    campeonatosConstructores: 0
  },
  {
    id: 'team-alpine',
    nombre: 'BWT Alpine F1 Team',
    nombreCompleto: 'BWT Alpine Formula One Team',
    pais: 'Francia / Reino Unido',
    sede: 'Enstone, Oxfordshire, Reino Unido',
    directorEquipo: 'Oliver Oakes',
    directorTecnico: 'David Sanchez',
    chasis: 'A526',
    unidadPotencia: 'Renault E-Tech RE26',
    colorPrimario: '#0090FF',
    colorSecundario: '#FF87BC',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 95,
    posicionCampeonato: 6,
    campeonatosConstructores: 2
  },
  {
    id: 'team-williams',
    nombre: 'Williams Racing',
    nombreCompleto: 'Williams Grand Prix Engineering',
    pais: 'Reino Unido',
    sede: 'Grove, Oxfordshire, Reino Unido',
    directorEquipo: 'James Vowles',
    directorTecnico: 'Pat Fry',
    chasis: 'FW48',
    unidadPotencia: 'Mercedes-AMG M17 E Performance',
    colorPrimario: '#00A0DE',
    colorSecundario: '#041E42',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 110,
    posicionCampeonato: 7,
    campeonatosConstructores: 9
  },
  {
    id: 'team-rb',
    nombre: 'Visa Cash App RB F1 Team',
    nombreCompleto: 'Visa Cash App RB Formula One Team',
    pais: 'Italia',
    sede: 'Faenza, Rávena, Italia',
    directorEquipo: 'Laurent Mekies',
    directorTecnico: 'Jody Egginton',
    chasis: 'VCARB 03',
    unidadPotencia: 'Honda RBPT RBPTH003',
    colorPrimario: '#1634CB',
    colorSecundario: '#FFFFFF',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 50,
    posicionCampeonato: 8,
    campeonatosConstructores: 0
  },
  {
    id: 'team-haas',
    nombre: 'MoneyGram Haas F1 Team',
    nombreCompleto: 'MoneyGram Haas F1 Team',
    pais: 'Estados Unidos',
    sede: 'Kannapolis, Carolina del Norte, EE.UU.',
    directorEquipo: 'Ayao Komatsu',
    directorTecnico: 'Andrea De Zordo',
    chasis: 'VF-26',
    unidadPotencia: 'Ferrari 066/12 V6 Turbo Híbrido',
    colorPrimario: '#DA291C',
    colorSecundario: '#FFFFFF',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 48,
    posicionCampeonato: 9,
    campeonatosConstructores: 0
  },
  {
    id: 'team-sauber',
    nombre: 'Stake F1 Team Kick Sauber',
    nombreCompleto: 'Stake F1 Team Kick Sauber (Audi F1)',
    pais: 'Suiza / Alemania',
    sede: 'Hinwil, Zúrich, Suiza',
    directorEquipo: 'Mattia Binotto',
    directorTecnico: 'James Key',
    chasis: 'C46',
    unidadPotencia: 'Ferrari / Audi Power Unit',
    colorPrimario: '#52E252',
    colorSecundario: '#000000',
    logoUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=100&auto=format&fit=crop&q=60',
    puntosTotales: 40,
    posicionCampeonato: 10,
    campeonatosConstructores: 0
  }
];

export const INITIAL_DRIVERS = [
  // Ferrari
  {
    id: 'drv-leclerc',
    nombre: 'Charles',
    apellido: 'Leclerc',
    numero: 16,
    sigla: 'LEC',
    nacionalidad: 'Mónaco',
    banderaPais: '🇲🇨',
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1997-10-16',
    puntos: 195,
    podios: 38,
    victorias: 7,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-hamilton',
    nombre: 'Lewis',
    apellido: 'Hamilton',
    numero: 44,
    sigla: 'HAM',
    nacionalidad: 'Reino Unido',
    banderaPais: '🇬🇧',
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1985-01-07',
    puntos: 185,
    podios: 202,
    victorias: 105,
    campeonatos: 7,
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-bearman-res',
    nombre: 'Oliver',
    apellido: 'Bearman',
    numero: 38,
    sigla: 'BEA',
    nacionalidad: 'Reino Unido',
    banderaPais: '🇬🇧',
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    rol: DRIVER_ROLES.SUPLENTE,
    fechaNacimiento: '2005-05-08',
    puntos: 6,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Red Bull
  {
    id: 'drv-verstappen',
    nombre: 'Max',
    apellido: 'Verstappen',
    numero: 1,
    sigla: 'VER',
    nacionalidad: 'Países Bajos',
    banderaPais: '🇳🇱',
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1997-09-30',
    puntos: 220,
    podios: 108,
    victorias: 62,
    campeonatos: 4,
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-perez',
    nombre: 'Sergio',
    apellido: 'Pérez',
    numero: 11,
    sigla: 'PER',
    nacionalidad: 'México',
    banderaPais: '🇲🇽',
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1990-01-26',
    puntos: 145,
    podios: 39,
    victorias: 6,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-lawson',
    nombre: 'Liam',
    apellido: 'Lawson',
    numero: 30,
    sigla: 'LAW',
    nacionalidad: 'Nueva Zelanda',
    banderaPais: '🇳🇿',
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    rol: DRIVER_ROLES.SUPLENTE,
    fechaNacimiento: '2002-02-11',
    puntos: 2,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // McLaren
  {
    id: 'drv-norris',
    nombre: 'Lando',
    apellido: 'Norris',
    numero: 4,
    sigla: 'NOR',
    nacionalidad: 'Reino Unido',
    banderaPais: '🇬🇧',
    escuderiaId: 'team-mclaren',
    escuderiaNombre: 'McLaren Formula 1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1999-11-13',
    puntos: 190,
    podios: 24,
    victorias: 3,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-piastri',
    nombre: 'Oscar',
    apellido: 'Piastri',
    numero: 81,
    sigla: 'PIA',
    nacionalidad: 'Australia',
    banderaPais: '🇦🇺',
    escuderiaId: 'team-mclaren',
    escuderiaNombre: 'McLaren Formula 1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2001-04-06',
    puntos: 150,
    podios: 9,
    victorias: 2,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Mercedes
  {
    id: 'drv-russell',
    nombre: 'George',
    apellido: 'Russell',
    numero: 63,
    sigla: 'RUS',
    nacionalidad: 'Reino Unido',
    banderaPais: '🇬🇧',
    escuderiaId: 'team-mercedes',
    escuderiaNombre: 'Mercedes-AMG PETRONAS',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1998-02-15',
    puntos: 160,
    podios: 15,
    victorias: 2,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-antonelli',
    nombre: 'Kimi',
    apellido: 'Antonelli',
    numero: 12,
    sigla: 'ANT',
    nacionalidad: 'Italia',
    banderaPais: '🇮🇹',
    escuderiaId: 'team-mercedes',
    escuderiaNombre: 'Mercedes-AMG PETRONAS',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2006-08-25',
    puntos: 130,
    podios: 3,
    victorias: 1,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Aston Martin
  {
    id: 'drv-alonso',
    nombre: 'Fernando',
    apellido: 'Alonso',
    numero: 14,
    sigla: 'ALO',
    nacionalidad: 'España',
    banderaPais: '🇪🇸',
    escuderiaId: 'team-astonmartin',
    escuderiaNombre: 'Aston Martin Aramco F1',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1981-07-29',
    puntos: 80,
    podios: 106,
    victorias: 32,
    campeonatos: 2,
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-stroll',
    nombre: 'Lance',
    apellido: 'Stroll',
    numero: 18,
    sigla: 'STR',
    nacionalidad: 'Canadá',
    banderaPais: '🇨🇦',
    escuderiaId: 'team-astonmartin',
    escuderiaNombre: 'Aston Martin Aramco F1',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1998-10-29',
    puntos: 40,
    podios: 3,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Alpine (con Franco Colapinto y Pierre Gasly)
  {
    id: 'drv-gasly',
    nombre: 'Pierre',
    apellido: 'Gasly',
    numero: 10,
    sigla: 'GAS',
    nacionalidad: 'Francia',
    banderaPais: '🇫🇷',
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1996-02-07',
    puntos: 50,
    podios: 4,
    victorias: 1,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-colapinto',
    nombre: 'Franco',
    apellido: 'Colapinto',
    numero: 43,
    sigla: 'COL',
    nacionalidad: 'Argentina',
    banderaPais: '🇦🇷',
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2003-05-27',
    puntos: 45,
    podios: 1,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-doohan',
    nombre: 'Jack',
    apellido: 'Doohan',
    numero: 61,
    sigla: 'DOO',
    nacionalidad: 'Australia',
    banderaPais: '🇦🇺',
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    rol: DRIVER_ROLES.SUPLENTE,
    fechaNacimiento: '2003-01-20',
    puntos: 0,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Williams
  {
    id: 'drv-sainz',
    nombre: 'Carlos',
    apellido: 'Sainz',
    numero: 55,
    sigla: 'SAI',
    nacionalidad: 'España',
    banderaPais: '🇪🇸',
    escuderiaId: 'team-williams',
    escuderiaNombre: 'Williams Racing',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1994-09-01',
    puntos: 75,
    podios: 25,
    victorias: 4,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-albon',
    nombre: 'Alexander',
    apellido: 'Albon',
    numero: 23,
    sigla: 'ALB',
    nacionalidad: 'Tailandia',
    banderaPais: '🇹🇭',
    escuderiaId: 'team-williams',
    escuderiaNombre: 'Williams Racing',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1996-03-23',
    puntos: 35,
    podios: 2,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Visa Cash App RB
  {
    id: 'drv-tsunoda',
    nombre: 'Yuki',
    apellido: 'Tsunoda',
    numero: 22,
    sigla: 'TSU',
    nacionalidad: 'Japón',
    banderaPais: '🇯🇵',
    escuderiaId: 'team-rb',
    escuderiaNombre: 'Visa Cash App RB F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2000-05-11',
    puntos: 30,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-hadjar',
    nombre: 'Isack',
    apellido: 'Hadjar',
    numero: 6,
    sigla: 'HAD',
    nacionalidad: 'Francia',
    banderaPais: '🇫🇷',
    escuderiaId: 'team-rb',
    escuderiaNombre: 'Visa Cash App RB F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2004-09-28',
    puntos: 20,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Haas
  {
    id: 'drv-ocon',
    nombre: 'Esteban',
    apellido: 'Ocon',
    numero: 31,
    sigla: 'OCO',
    nacionalidad: 'Francia',
    banderaPais: '🇫🇷',
    escuderiaId: 'team-haas',
    escuderiaNombre: 'MoneyGram Haas F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1996-09-17',
    puntos: 30,
    podios: 4,
    victorias: 1,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-bearman-haas',
    nombre: 'Oliver',
    apellido: 'Bearman',
    numero: 87,
    sigla: 'BEA',
    nacionalidad: 'Reino Unido',
    banderaPais: '🇬🇧',
    escuderiaId: 'team-haas',
    escuderiaNombre: 'MoneyGram Haas F1 Team',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2005-05-08',
    puntos: 18,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  // Stake Sauber
  {
    id: 'drv-hulkenberg',
    nombre: 'Nico',
    apellido: 'Hülkenberg',
    numero: 27,
    sigla: 'HUL',
    nacionalidad: 'Alemania',
    banderaPais: '🇩🇪',
    escuderiaId: 'team-sauber',
    escuderiaNombre: 'Stake F1 Team Kick Sauber',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '1987-08-19',
    puntos: 25,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=60',
    activo: true
  },
  {
    id: 'drv-bortoleto',
    nombre: 'Gabriel',
    apellido: 'Bortoleto',
    numero: 5,
    sigla: 'BOR',
    nacionalidad: 'Brasil',
    banderaPais: '🇧🇷',
    escuderiaId: 'team-sauber',
    escuderiaNombre: 'Stake F1 Team Kick Sauber',
    rol: DRIVER_ROLES.TITULAR,
    fechaNacimiento: '2004-10-14',
    puntos: 15,
    podios: 0,
    victorias: 0,
    campeonatos: 0,
    fotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=60',
    activo: true
  }
];

export const INITIAL_CARS = [
  {
    id: 'car-sf26-16',
    numeroAuto: 16,
    modelo: 'SF-26 Chasis #01',
    chasisCodigo: 'FER-2026-001',
    motorCodigo: '066/12-PU-01',
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    pilotoId: 'drv-leclerc',
    pilotoNombre: 'Charles Leclerc',
    pesoKg: 798.4,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Monoplaza certificado conforme a normativa técnica 2026.'
  },
  {
    id: 'car-sf26-44',
    numeroAuto: 44,
    modelo: 'SF-26 Chasis #02',
    chasisCodigo: 'FER-2026-002',
    motorCodigo: '066/12-PU-02',
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    pilotoId: 'drv-hamilton',
    pilotoNombre: 'Lewis Hamilton',
    pesoKg: 798.2,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Asiento y cockpit adaptados a especificaciones FIA.'
  },
  {
    id: 'car-rb22-01',
    numeroAuto: 1,
    modelo: 'RB22 Chasis #01',
    chasisCodigo: 'RBR-2026-001',
    motorCodigo: 'HRC-RBPTH003-01',
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    pilotoId: 'drv-verstappen',
    pilotoNombre: 'Max Verstappen',
    pesoKg: 798.1,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Alerón delantero verificado en túnel de viento FIA.'
  },
  {
    id: 'car-mcl39-04',
    numeroAuto: 4,
    modelo: 'MCL39 Chasis #01',
    chasisCodigo: 'MCL-2026-001',
    motorCodigo: 'M17-PU-01',
    escuderiaId: 'team-mclaren',
    escuderiaNombre: 'McLaren Formula 1 Team',
    pilotoId: 'drv-norris',
    pilotoNombre: 'Lando Norris',
    pesoKg: 798.5,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Suelo y difusor aprobados.'
  },
  {
    id: 'car-a526-43',
    numeroAuto: 43,
    modelo: 'Alpine A526 Chasis #01',
    chasisCodigo: 'ALP-2026-001',
    motorCodigo: 'RE26-PU-01',
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    pilotoId: 'drv-colapinto',
    pilotoNombre: 'Franco Colapinto',
    pesoKg: 798.0,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Monoplaza y telemetría homologados por comisarios FIA.'
  },
  {
    id: 'car-a526-10',
    numeroAuto: 10,
    modelo: 'Alpine A526 Chasis #02',
    chasisCodigo: 'ALP-2026-002',
    motorCodigo: 'RE26-PU-02',
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    pilotoId: 'drv-gasly',
    pilotoNombre: 'Pierre Gasly',
    pesoKg: 798.2,
    estado: CAR_STATUS.HOMOLOGATED,
    observacionesTecnicas: 'Cockpit y halo de seguridad verificados.'
  }
];

export const INITIAL_EVENTS = [
  {
    id: 'evt-2026-01',
    nombre: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Bahrain International Circuit',
    ciudad: 'Sakhir',
    pais: 'Bahréin',
    banderaPais: '🇧🇭',
    fechaInicio: '2026-03-06',
    fechaFin: '2026-03-08',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.COMPLETED,
    roundNumero: 1,
    distanciaKm: 308.238,
    vueltas: 57,
    longitudCircuitoKm: 5.412,
    recordVuelta: '1:31.447',
    recordPiloto: 'Pedro de la Rosa (2005)',
    descripcion: 'Gran Premio inaugural de la temporada 2026 bajo los reflectores de Sakhir.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: true
  },
  {
    id: 'evt-2026-02',
    nombre: 'FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Jeddah Corniche Circuit',
    ciudad: 'Yeda',
    pais: 'Arabia Saudita',
    banderaPais: '🇸🇦',
    fechaInicio: '2026-03-20',
    fechaFin: '2026-03-22',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.COMPLETED,
    roundNumero: 2,
    distanciaKm: 308.450,
    vueltas: 50,
    longitudCircuitoKm: 6.174,
    recordVuelta: '1:30.734',
    recordPiloto: 'Lewis Hamilton (2021)',
    descripcion: 'El circuito urbano más rápido del calendario mundial.',
    imagenCircuito: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: true
  },
  {
    id: 'evt-2026-tire-01',
    nombre: 'PRUEBA OFICIAL DE NEUMÁTICOS PIRELLI #1 (INICIO DE AÑO)',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Bahrain International Circuit',
    ciudad: 'Sakhir',
    pais: 'Bahréin',
    banderaPais: '🇧🇭',
    fechaInicio: '2026-03-24',
    fechaFin: '2026-03-25',
    tipoEvento: EVENT_TYPES.TIRE_TEST,
    estado: EVENT_STATUS.COMPLETED,
    roundNumero: 0,
    distanciaKm: 450.0,
    vueltas: 85,
    longitudCircuitoKm: 5.412,
    descripcion: 'Primera prueba oficial anual de neumáticos obligatoria por la FIA. Evaluación ciega de compuestos duros y medios C1-C3.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    proveedorOficial: 'Pirelli Motorsport',
    compuestosEvaluados: [PIRELLI_COMPOUNDS.C1, PIRELLI_COMPOUNDS.C2, PIRELLI_COMPOUNDS.C3],
    objetivoPrueba: 'Monitoreo de desgaste térmico en asfalto abrasivo.',
    temperaturaPistaObjetivoC: 42,
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-03',
    nombre: 'FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Albert Park Circuit',
    ciudad: 'Melbourne',
    pais: 'Australia',
    banderaPais: '🇦🇺',
    fechaInicio: '2026-04-10',
    fechaFin: '2026-04-12',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.COMPLETED,
    roundNumero: 3,
    distanciaKm: 306.124,
    vueltas: 58,
    longitudCircuitoKm: 5.278,
    recordVuelta: '1:19.813',
    recordPiloto: 'Charles Leclerc (2024)',
    descripcion: 'Carrera vibrante en el pintoresco parque de Albert Park.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: true
  },
  {
    id: 'evt-2026-04',
    nombre: 'FORMULA 1 GRAND PRIX DE MONACO 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Circuit de Monaco',
    ciudad: 'Montecarlo',
    pais: 'Mónaco',
    banderaPais: '🇲🇨',
    fechaInicio: '2026-05-22',
    fechaFin: '2026-05-24',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.COMPLETED,
    roundNumero: 4,
    distanciaKm: 260.286,
    vueltas: 78,
    longitudCircuitoKm: 3.337,
    recordVuelta: '1:12.909',
    recordPiloto: 'Lewis Hamilton (2021)',
    descripcion: 'La joya de la corona del automovilismo mundial.',
    imagenCircuito: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: true
  },
  {
    id: 'evt-2026-05',
    nombre: 'FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Silverstone Circuit',
    ciudad: 'Silverstone',
    pais: 'Reino Unido',
    banderaPais: '🇬🇧',
    fechaInicio: '2026-07-03',
    fechaFin: '2026-07-05',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.IN_PROGRESS,
    roundNumero: 5,
    distanciaKm: 306.198,
    vueltas: 52,
    longitudCircuitoKm: 5.891,
    recordVuelta: '1:27.097',
    recordPiloto: 'Max Verstappen (2020)',
    descripcion: 'El hogar legendario de la velocidad y curvas de alta exigencia G.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-tire-02',
    nombre: 'PRUEBA OFICIAL DE NEUMÁTICOS PIRELLI #2 (MITAD DE TEMPORADA)',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Silverstone Circuit',
    ciudad: 'Silverstone',
    pais: 'Reino Unido',
    banderaPais: '🇬🇧',
    fechaInicio: '2026-07-07',
    fechaFin: '2026-07-08',
    tipoEvento: EVENT_TYPES.TIRE_TEST,
    estado: EVENT_STATUS.SCHEDULED,
    roundNumero: 0,
    distanciaKm: 420.0,
    vueltas: 72,
    longitudCircuitoKm: 5.891,
    descripcion: 'Segunda prueba oficial estipulada por reglamento FIA para testeo de compuestos blandos C4-C5 y lluvia extrema.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    proveedorOficial: 'Pirelli Motorsport',
    compuestosEvaluados: [PIRELLI_COMPOUNDS.C4, PIRELLI_COMPOUNDS.C5, PIRELLI_COMPOUNDS.WET],
    objetivoPrueba: 'Optimización de compuestos ultrablandos y lluvia para la segunda mitad del campeonato.',
    temperaturaPistaObjetivoC: 28,
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-06',
    nombre: 'FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026',
    categoria: FIA_CATEGORIES.F1,
    circuito: 'Autodromo Nazionale Monza',
    ciudad: 'Monza',
    pais: 'Italia',
    banderaPais: '🇮🇹',
    fechaInicio: '2026-09-04',
    fechaFin: '2026-09-06',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.SCHEDULED,
    roundNumero: 6,
    distanciaKm: 306.720,
    vueltas: 53,
    longitudCircuitoKm: 5.793,
    recordVuelta: '1:21.046',
    recordPiloto: 'Rubens Barrichello (2004)',
    descripcion: 'El Templo de la Velocidad con pasión ferrarista inigualable.',
    imagenCircuito: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-f2-01',
    nombre: 'FIA FORMULA 2 CHAMPIONSHIP - SILVERSTONE ROUND',
    categoria: FIA_CATEGORIES.F2,
    circuito: 'Silverstone Circuit',
    ciudad: 'Silverstone',
    pais: 'Reino Unido',
    banderaPais: '🇬🇧',
    fechaInicio: '2026-07-04',
    fechaFin: '2026-07-05',
    tipoEvento: EVENT_TYPES.SPRINT_WEEKEND,
    estado: EVENT_STATUS.SCHEDULED,
    roundNumero: 7,
    distanciaKm: 170.0,
    vueltas: 29,
    longitudCircuitoKm: 5.891,
    descripcion: 'Sprint y Feature Race de la categoría antesala a la Fórmula 1.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-f3-01',
    nombre: 'FIA FORMULA 3 CHAMPIONSHIP - SPA-FRANCORCHAMPS',
    categoria: FIA_CATEGORIES.F3,
    circuito: 'Circuit de Spa-Francorchamps',
    ciudad: 'Stavelot',
    pais: 'Bélgica',
    banderaPais: '🇧🇪',
    fechaInicio: '2026-07-24',
    fechaFin: '2026-07-26',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.SCHEDULED,
    roundNumero: 8,
    distanciaKm: 150.0,
    vueltas: 22,
    longitudCircuitoKm: 7.004,
    descripcion: 'Jóvenes promesas compitiendo en el mítico Raidillon y Eau Rouge.',
    imagenCircuito: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: false
  },
  {
    id: 'evt-2026-f1a-01',
    nombre: 'F1 ACADEMY - CIRCUIT DE BARCELONA-CATALUNYA',
    categoria: FIA_CATEGORIES.F1_ACADEMY,
    circuito: 'Circuit de Barcelona-Catalunya',
    ciudad: 'Montmeló, Barcelona',
    pais: 'España',
    banderaPais: '🇪🇸',
    fechaInicio: '2026-05-29',
    fechaFin: '2026-05-31',
    tipoEvento: EVENT_TYPES.GRAND_PRIX,
    estado: EVENT_STATUS.SCHEDULED,
    roundNumero: 3,
    distanciaKm: 120.0,
    vueltas: 18,
    longitudCircuitoKm: 4.657,
    descripcion: 'Campeonato oficial femenino de monoplazas impulsado por la FIA.',
    imagenCircuito: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=60',
    puntajesRegistrados: false
  }
];

export const INITIAL_RACE_RESULTS = [
  // Round 1: Bahrain
  {
    id: 'res-01-01',
    eventoId: 'evt-2026-01',
    eventoNombre: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026',
    pilotoId: 'drv-verstappen',
    pilotoNombre: 'Max Verstappen',
    pilotoNumero: 1,
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    posicion: 1,
    tiempoTotal: '1:31:44.742',
    puntos: 25, // 25 PTS (Sin punto por vuelta rápida según reglamento FIA 2026)
    puntosEscuderia: 25,
    vueltaRapida: true,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-03-08T20:15:00Z'
  },
  {
    id: 'res-01-02',
    eventoId: 'evt-2026-01',
    eventoNombre: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026',
    pilotoId: 'drv-leclerc',
    pilotoNombre: 'Charles Leclerc',
    pilotoNumero: 16,
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    posicion: 2,
    tiempoTotal: '+4.250s',
    puntos: 18,
    puntosEscuderia: 18,
    vueltaRapida: false,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-03-08T20:20:00Z'
  },
  {
    id: 'res-01-03',
    eventoId: 'evt-2026-01',
    eventoNombre: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026',
    pilotoId: 'drv-hamilton',
    pilotoNombre: 'Lewis Hamilton',
    pilotoNumero: 44,
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    posicion: 3,
    tiempoTotal: '+7.810s',
    puntos: 15,
    puntosEscuderia: 15,
    vueltaRapida: false,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-03-08T20:20:00Z'
  },
  {
    id: 'res-01-04',
    eventoId: 'evt-2026-01',
    eventoNombre: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026',
    pilotoId: 'drv-norris',
    pilotoNombre: 'Lando Norris',
    pilotoNumero: 4,
    escuderiaId: 'team-mclaren',
    escuderiaNombre: 'McLaren Formula 1 Team',
    posicion: 4,
    tiempoTotal: '+12.440s',
    puntos: 12,
    puntosEscuderia: 12,
    vueltaRapida: false,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-03-08T20:22:00Z'
  },
  // Round 2: Monaco (Round 4 in calendar, but played early in demo)
  {
    id: 'res-04-01',
    eventoId: 'evt-2026-04',
    eventoNombre: 'FORMULA 1 GRAND PRIX DE MONACO 2026',
    pilotoId: 'drv-leclerc',
    pilotoNombre: 'Charles Leclerc',
    pilotoNumero: 16,
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    posicion: 1,
    tiempoTotal: '1:45:32.110',
    puntos: 25,
    puntosEscuderia: 25,
    vueltaRapida: false,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-05-24T18:00:00Z'
  },
  {
    id: 'res-04-02',
    eventoId: 'evt-2026-04',
    eventoNombre: 'FORMULA 1 GRAND PRIX DE MONACO 2026',
    pilotoId: 'drv-piastri',
    pilotoNombre: 'Oscar Piastri',
    pilotoNumero: 81,
    escuderiaId: 'team-mclaren',
    escuderiaNombre: 'McLaren Formula 1 Team',
    posicion: 2,
    tiempoTotal: '+1.884s',
    puntos: 18,
    puntosEscuderia: 18,
    vueltaRapida: false,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: true,
    fechaNotificacion: '2026-05-24T18:05:00Z'
  },
  {
    id: 'res-04-03',
    eventoId: 'evt-2026-04',
    eventoNombre: 'FORMULA 1 GRAND PRIX DE MONACO 2026',
    pilotoId: 'drv-hamilton',
    pilotoNombre: 'Lewis Hamilton',
    pilotoNumero: 44,
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    posicion: 3,
    tiempoTotal: '+3.120s',
    puntos: 15, // 15 PTS (Sin punto por vuelta rápida según reglamento FIA 2026)
    puntosEscuderia: 15,
    vueltaRapida: true,
    estadoFinal: RACE_STATUS.FINISHED,
    notificadoEscuderia: false, // Pending ack for demo!
    fechaNotificacion: null
  }
];

export const INITIAL_USERS = [
  {
    id: 'usr-admin-fia',
    nombre: 'Mohammed Ben Sulayem / Niels Wittich',
    email: 'race.director@fia.com',
    rol: USER_ROLES.ADMIN_FIA,
    cargo: 'Presidente / Director de Carrera FIA',
    departamento: 'Dirección de Carrera y Seguridad',
    licenciaFIA: 'FIA-SUPER-COMM-001',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    activo: true
  },
  {
    id: 'usr-admin-ferrari',
    nombre: 'Frédéric Vasseur',
    email: 'fvasseur@ferrari.com',
    rol: USER_ROLES.ADMIN_ESCUDERIA,
    escuderiaId: 'team-ferrari',
    escuderiaNombre: 'Scuderia Ferrari HP',
    cargoEquipo: 'Team Principal & Managing Director',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    activo: true
  },
  {
    id: 'usr-admin-redbull',
    nombre: 'Christian Horner',
    email: 'chorner@redbullracing.com',
    rol: USER_ROLES.ADMIN_ESCUDERIA,
    escuderiaId: 'team-redbull',
    escuderiaNombre: 'Oracle Red Bull Racing',
    cargoEquipo: 'Team Principal & CEO',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    activo: true
  },
  {
    id: 'usr-admin-alpine',
    nombre: 'Oliver Oakes / Flavio Briatore',
    email: 'ooakes@alpinef1.com',
    rol: USER_ROLES.ADMIN_ESCUDERIA,
    escuderiaId: 'team-alpine',
    escuderiaNombre: 'BWT Alpine F1 Team',
    cargoEquipo: 'Team Principal & Executive Advisor',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    activo: true
  },
  {
    id: 'usr-public-fan',
    nombre: 'Aficionado F1 Internacional',
    email: 'fan.motorsport@grandprix.com',
    rol: USER_ROLES.PUBLICO,
    escuderiaFavorita: 'Scuderia Ferrari HP',
    recibirAlertas: true,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    activo: true
  }
];
